export const templates = [
    {
        _id: '68ddecdbc9474e23bb5e914b',
        color: '#C03B22',
        properties: [
            {
                _id: '68ddecdbc9474e23bb5e914c',
                type: 'text',
                label: 'Text Label',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'text_label',
            },
            {
                _id: '68ddecdbc9474e23bb5e914d',
                type: 'markdown',
                label: 'Markdown',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'markdown',
            },
            {
                _id: '68ddecdbc9474e23bb5e914e',
                type: 'date',
                label: 'Date',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'date',
            },
            {
                _id: '68e5e13b192fccdd10036334',
                type: 'geolocation',
                label: 'GeolocationIsolated',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'geolocationisolated_geolocation',
            },
            {
                _id: '68ddecdbc9474e23bb5e914f',
                type: 'multidate',
                label: 'Multidate',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'multidate',
            },
            {
                _id: '68ddecdbc9474e23bb5e9150',
                type: 'daterange',
                label: 'Daterange',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'daterange',
            },
            {
                _id: '68e56b29192fccdd10035c2a',
                type: 'multidaterange',
                label: 'Multidaterange',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'multidaterange',
            },
            {
                content: '68d6ed4891b591b7432b276b',
                _id: '68ddecdbc9474e23bb5e9151',
                type: 'select',
                label: 'Select',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'select',
            },
            {
                content: '68d6ed4891b591b7432b276b',
                _id: '68ddecdbc9474e23bb5e9152',
                type: 'multiselect',
                label: 'Multiselect',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'multiselect',
            },
            {
                content: '5bfbb1a0471dd0fc16ada146',
                _id: '68ddecdbc9474e23bb5e9153',
                type: 'relationship',
                label: 'Relationship',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                relationType: '68da99b961bceda4fe0d6ddd',
                inherit: {
                    property: '68d6f62891b591b7432b2b4b',
                    type: 'multiselect',
                },
                generatedId: false,
                name: 'relationship',
            },
            {
                content: '5bfbb1a0471dd0fc16ada146',
                _id: '68e585e4192fccdd10035da9',
                type: 'relationship',
                label: 'Relationship1',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                relationType: '68da99b961bceda4fe0d6ddd',
                generatedId: false,
                name: 'relationship1',
            },
            {
                _id: '68ddecdbc9474e23bb5e9154',
                type: 'link',
                label: 'Link',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'link',
            },
            {
                _id: '68ddecdbc9474e23bb5e9155',
                type: 'image',
                label: 'Image',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: 'fill',
                generatedId: false,
                name: 'image',
            },
            {
                _id: '68ddecdbc9474e23bb5e9156',
                type: 'preview',
                label: 'Preview',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: 'fill',
                generatedId: false,
                name: 'preview',
            },
            {
                _id: '68ddecdbc9474e23bb5e9157',
                type: 'media',
                label: 'Media',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'media',
            },
            {
                _id: '68ddecdbc9474e23bb5e9158',
                type: 'geolocation',
                label: 'Geolocation',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'geolocation_geolocation',
            },
            {
                _id: '68e5e0d9192fccdd100361d3',
                type: 'geolocation',
                label: 'Geolocation2',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'geolocation2_geolocation',
            },
            {
                content: '5bfbb1a0471dd0fc16ada146',
                _id: '68e5e119192fccdd100362cb',
                type: 'relationship',
                label: 'GeolocationR',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                relationType: '68da99b961bceda4fe0d6ddd',
                inherit: {
                    property: '68e5e0eb192fccdd1003624b',
                    type: 'geolocation',
                },
                generatedId: false,
                name: 'geolocationr',
            },
            {
                _id: '68ddecdbc9474e23bb5e9159',
                type: 'generatedid',
                label: 'Generatedid',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'generatedid',
            },
        ],
        commonProperties: [
            {
                _id: '68ddecdbc9474e23bb5e915a',
                label: 'Title',
                name: 'title',
                type: 'text',
                isCommonProperty: true,
            },
            {
                _id: '68ddecdbc9474e23bb5e915b',
                label: 'Date added',
                name: 'creationDate',
                type: 'date',
                isCommonProperty: true,
            },
            {
                _id: '68ddecdbc9474e23bb5e915c',
                label: 'Date modified',
                name: 'editDate',
                type: 'date',
                isCommonProperty: true,
            },
        ],
        entityViewPage: '',
        name: 'Full template',
        __v: 5,
    },

    {
        _id: '5bfbb1a0471dd0fc16ada146',
        name: 'Document',
        commonProperties: [
            {
                _id: '5bfbb1a0471dd0fc16ada148',
                label: 'Title',
                name: 'title',
                isCommonProperty: true,
                type: 'text',
                prioritySorting: false,
            },
            {
                _id: '5bfbb1a0471dd0fc16ada147',
                label: 'Date added',
                name: 'creationDate',
                isCommonProperty: true,
                type: 'date',
                prioritySorting: false,
            },
            {
                _id: '68da9640ea8d8c69971bf274',
                label: 'Date modified',
                name: 'editDate',
                type: 'date',
                isCommonProperty: true,
            },
        ],
        properties: [
            {
                _id: '68d56f072489957bf47a600b',
                type: 'date',
                label: 'Date',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'date',
            },
            {
                content: '68d6ed4891b591b7432b276b',
                _id: '68d6f62891b591b7432b2b4b',
                type: 'multiselect',
                label: 'Multiselect',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'multiselect',
            },
            {
                _id: '68da993261bceda4fe0d6c49',
                type: 'markdown',
                label: 'Markdown',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'markdown',
            },
            {
                content: '68d6ed4891b591b7432b276b',
                _id: '68daaa5561bceda4fe1014d8',
                type: 'multiselect',
                label: 'Multiselect from text',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'multiselect_from_text',
            },
            {
                _id: '68e5e0eb192fccdd1003624b',
                type: 'geolocation',
                label: 'GeolocationD',
                noLabel: false,
                required: false,
                showInCard: false,
                filter: false,
                defaultfilter: false,
                prioritySorting: false,
                style: '',
                generatedId: false,
                name: 'geolocationd_geolocation',
            },
        ],
        __v: 8,
        default: false,
        color: '#16bdca',
        entityViewPage: '',
    },
];

export const settings = {
    _id: '58ad7d240d44252fee4e6213',
    site_name: 'Uwazi',
    filters: [],
    links: [],
    languages: [
        {
            _id: '58ad7d240d44252fee4e6214',
            default: true,
            label: 'English',
            key: 'en',
            localized_label: 'English',
        },
        {
            _id: '68d5a6ecb35c48bcf414c57e',
            label: 'Russian',
            key: 'ru',
            ISO639_3: 'rus',
            elastic: 'russian',
            ISO639_1: 'ru',
            localized_label: 'Русский',
            translationAvailable: true,
        },
        {
            _id: '68d5a6f4b35c48bcf414cd27',
            label: 'Spanish',
            key: 'es',
            ISO639_3: 'spa',
            elastic: 'spanish',
            ISO639_1: 'es',
            localized_label: 'Español',
            translationAvailable: true,
        },
        {
            _id: '68d5a80eb35c48bcf414d6b7',
            label: 'Greek',
            key: 'el',
            ISO639_3: 'ell',
            elastic: 'greek',
            ISO639_1: 'el',
            localized_label: 'Ελληνικά',
            translationAvailable: false,
        },
    ],
    __v: 5,
    newNameGeneration: true,
    private: false,
    mapLayers: ['Streets', 'Hybrid', 'Satellite'],
    allowcustomJS: false,
    allowedPublicTemplates: ['68d16b182afcebbf30e6fa53'],
    analyticsTrackingId: '',
    contactEmail: '',
    cookiepolicy: false,
    dateFormat: 'yyyy/MM/dd',
    defaultLibraryView: 'cards',
    favicon: '',
    home_page: '',
    mapApiKey: '',
    mapStartingPoint: [
        {
            lon: 6,
            lat: 46,
        },
    ],
    matomoConfig: '',
    openPublicEndpoint: false,
    publicFormDestination: '',
    senderEmail: '',
    tilesProvider: 'mapbox',
    features: {
        paragraphExtraction: true,
        'metadata-extraction': true,
        metadataExtraction: {
            url: 'http://127.0.0.1:5056',
        },
        segmentation: {
            url: 'http://127.0.0.1:5051/async_extraction',
        },
    },
};

export const translations = [{
    locale: 'en',
    contexts: [
        {
            id: '5bfbb1a0471dd0fc16ada146',
            label: 'Document',
            type: 'Entity',
            values: {
                Document: 'Document EN',
                Date: 'Date',
                Title: 'Title',
                Multiselect: 'Multiselect',
                Markdown: 'Markdown',
                'Multiselect from text': 'Multiselect from text',
                GeolocationD: 'GeolocationD',
            },
        },
        {
            id: '68d6ed4891b591b7432b276b',
            label: 'Verbs',
            type: 'Thesaurus',
            values: {
                Verbs: 'Verbs',
                Acknowledging: 'Acknowledging',
                Again: 'Again',
                Citing: 'Citing',
                Confirming: 'Confirming',
                Emphasizing: 'Emphasizing',
                Expressing: 'Expressing',
                'Guided by': 'Guided by',
                Noting: 'Noting',
                Observing: 'Observing',
                Reaffirming: 'Reaffirming',
                Recalling: 'Recalling',
                Recognizing: 'Recognizing',
                'Referring To': 'Referring To',
                Stating: 'Stating',
                'Taking Into Account': 'Taking Into Account',
                'Taking note': 'Taking note',
                Underscoring: 'Underscoring',
                Urges: 'Urges',
                Welcomes: 'Welcomes',
                Welcoming: 'Welcoming',
                grouped: 'grouped',
                verb1: 'verb1',
                verb2: 'verb2',
            },
        },
        {
            id: '68da997861bceda4fe0d6d25',
            label: 'TextDocument',
            type: 'Entity',
            values: {
                Numeric: 'Numeric',
                Markdown: 'Markdown',
                TextDocument: 'TextDocument',
                Title: 'Title',
                Multiselect: 'Multiselect',
            },
        },
        {
            id: '68da99b961bceda4fe0d6ddd',
            label: 'related from',
            type: 'Connection',
            values: {
                'related from': 'related from',
            },
        },
        {
            id: '68da99d961bceda4fe0d6e0f',
            label: 'related to',
            type: 'Relationship Type',
            values: {
                'related to': 'related to',
            },
        },
        {
            id: '68ddecdbc9474e23bb5e914b',
            label: 'Full template',
            type: 'Entity',
            values: {
                'Text Label': 'Text Label',
                Markdown: 'Markdown',
                Date: 'Date',
                Multidate: 'Multidate',
                Daterange: 'Daterange',
                Select: 'Select',
                Multiselect: 'Multiselect',
                Relationship: 'Relationship',
                Link: 'Link',
                Image: 'Image',
                Preview: 'Preview',
                Media: 'Media',
                Geolocation: 'Geolocation',
                Generatedid: 'Generatedid',
                'Full template': 'Full template',
                Title: 'Title',
                Multidaterange: 'Multidaterange',
                Relationship1: 'Relationship1',
                Geolocation2: 'Geolocation2',
                GeolocationR: 'GeolocationR',
                GeolocationIsolated: 'GeolocationIsolated',
            },
        },
    ],
}];

export const singleEntity = [
    {
        _id: '68dded72c9474e23bb5e9254',
        language: 'en',
        sharedId: '36l0vr92qce',
        title: 'Full entity',
        template: '68ddecdbc9474e23bb5e914b',
        published: false,
        creationDate: 1759374706197,
        editDate: 1759897673019,
        metadata: {
            text_label: [
                {
                    value: 'Text1',
                },
            ],
            markdown: [
                {
                    value:
                        '# A first-level heading\n## A second-level heading\n### A third-level heading\n',
                },
            ],
            date: [
                {
                    value: 1759363200,
                },
            ],
            geolocationisolated_geolocation: [
                {
                    value: {
                        lat: 46.3964365565104,
                        lon: 3.6694335937500004,
                        label: '',
                    },
                },
            ],
            multidate: [
                {
                    value: 1759276800,
                },
                {
                    value: 1759363200,
                },
                {
                    value: 1759449600,
                },
            ],
            daterange: [
                {
                    value: {
                        from: 1759276800,
                        to: 1761955199,
                    },
                },
            ],
            multidaterange: [
                {
                    value: {
                        from: 1759276800,
                        to: 1759449599,
                    },
                },
                {
                    value: {
                        from: 1759363200,
                        to: 1759535999,
                    },
                },
            ],
            select: [
                {
                    value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
                    label: 'Again',
                },
            ],
            multiselect: [
                {
                    value: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
                    label: 'Acknowledging',
                },
                {
                    value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
                    label: 'Again',
                },
                {
                    value: '8c418311-1244-4777-800a-65729b8c17a8',
                    label: 'verb2',
                    parent: {
                        value: '68979984-35ac-4b98-abf9-28eac857749c',
                        label: 'grouped',
                    },
                },
                {
                    value: 'e1b9944b-43ef-4989-837b-b3df79284b00',
                    label: 'verb1',
                    parent: {
                        value: '68979984-35ac-4b98-abf9-28eac857749c',
                        label: 'grouped',
                    },
                },
            ],
            relationship: [
                {
                    value: 'xjku67dv7b',
                    label: 'Context trimming sample2',
                    icon: {
                        _id: 'ECU',
                        label: 'Ecuador',
                        type: 'Flags',
                    },
                    type: 'entity',
                    inheritedValue: [
                        {
                            value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
                            label: 'Again',
                        },
                        {
                            value: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
                            label: 'Acknowledging',
                        },
                    ],
                    inheritedType: 'multiselect',
                },
                {
                    value: '4oklamamet',
                    label: 'Context trimming sample3',
                    icon: null,
                    type: 'entity',
                    inheritedValue: [],
                    inheritedType: 'multiselect',
                },
            ],
            relationship1: [
                {
                    value: 'xjku67dv7b',
                    label: 'Context trimming sample2',
                    icon: {
                        _id: 'ECU',
                        label: 'Ecuador',
                        type: 'Flags',
                    },
                    type: 'entity',
                },
                {
                    value: '4oklamamet',
                    label: 'Context trimming sample3',
                    icon: null,
                    type: 'entity',
                },
            ],
            link: [
                {
                    value: {
                        label: 'google',
                        url: 'www.google.com',
                    },
                },
            ],
            image: [
                {
                    value: '/api/files/17593747059321ygqk22fdos.png',
                },
            ],
            preview: [
                {
                    value: '',
                },
            ],
            media: [
                {
                    value:
                        '(/api/files/1759374705932xi5rx0mumef.mp4, {"timelinks":{"00:20:15":"control"}})',
                },
            ],
            geolocation_geolocation: [
                {
                    value: {
                        lat: 44.33301685687683,
                        lon: 5.998535156250001,
                        label: '',
                    },
                },
            ],
            geolocation2_geolocation: [
                {
                    value: {
                        lat: 62.58069554111894,
                        lon: 15.468750000000002,
                        label: '',
                    },
                },
            ],
            geolocationr: [
                {
                    value: 'xjku67dv7b',
                    label: 'Context trimming sample2',
                    icon: {
                        _id: 'ECU',
                        label: 'Ecuador',
                        type: 'Flags',
                    },
                    type: 'entity',
                    inheritedValue: [
                        {
                            value: {
                                lat: 43.80157978110818,
                                lon: 7.492675781250001,
                                label: '',
                            },
                        },
                    ],
                    inheritedType: 'geolocation',
                },
                {
                    value: '4oklamamet',
                    label: 'Context trimming sample3',
                    icon: null,
                    type: 'entity',
                    inheritedValue: [],
                    inheritedType: 'geolocation',
                },
            ],
            generatedid: [
                {
                    value: 'BDZ3505-3650',
                },
            ],
        },
        user: '58ada34d299e82674854510f',
        permissions: [
            {
                refId: '58ada34d299e82674854510f',
                type: 'user',
                level: 'write',
            },
        ],
        obsoleteMetadata: [],
        __v: 6,
        documents: [
            {
                _id: '68ddf0361980ce7868a57a0d',
                entity: '36l0vr92qce',
                type: 'document',
                filename: '1759375414087qpvllnq0588.pdf',
                originalname: 'g2505275.pdf',
                mimetype: 'application/pdf',
                size: 175109,
                status: 'ready',
                creationDate: 1759375414692,
                language: 'spa',
                toc: [],
                totalPages: 6,
            },
        ],
        attachments: [
            {
                _id: '68dded72c9474e23bb5e9278',
                entity: '36l0vr92qce',
                type: 'attachment',
                filename: '17593747059321ygqk22fdos.png',
                originalname: 'graph (5).png',
                mimetype: 'image/png',
                size: 28644,
                creationDate: 1759374706396,
            },
            {
                _id: '68dded72c9474e23bb5e927a',
                entity: '36l0vr92qce',
                type: 'attachment',
                filename: '1759374705932xi5rx0mumef.mp4',
                originalname: 'videoslideshow.mp4',
                mimetype: 'video/mp4',
                size: 52609674,
                creationDate: 1759374706399,
            },
        ],
    },
];